/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface SquareBtn {
    'clickTo': Function;
    'image': string;
    'text': string;
  }
  interface SquareBtnAttributes extends StencilHTMLAttributes {
    'clickTo'?: Function;
    'image'?: string;
    'onButtonClicked'?: (event: CustomEvent) => void;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SquareBtn': Components.SquareBtn;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'square-btn': Components.SquareBtnAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSquareBtnElement extends Components.SquareBtn, HTMLStencilElement {}
  var HTMLSquareBtnElement: {
    prototype: HTMLSquareBtnElement;
    new (): HTMLSquareBtnElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'square-btn': HTMLSquareBtnElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'square-btn': HTMLSquareBtnElement;
  }


}
